// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orders.WebAPI.DatabaseContext;

#nullable disable

namespace Orders.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230722040059_Price_DoubleToDecimal")]
    partial class Price_DoubleToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orders.WebAPI.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasFilter("[OrderNumber] IS NOT NULL");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            OrderID = new Guid("538b01e3-4803-4e4a-9f3c-8ffdfa6092ab"),
                            CustomerName = "Romy Jakoviljevic",
                            OrderDate = new DateTime(2022, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2022_1",
                            TotalAmount = 14m
                        },
                        new
                        {
                            OrderID = new Guid("e6f372d0-a5f5-42b0-b3a8-71726f489f51"),
                            CustomerName = "Dilly Grono",
                            OrderDate = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2022_3",
                            TotalAmount = 390m
                        },
                        new
                        {
                            OrderID = new Guid("c5cebf9d-8ca1-4f41-b85d-b2120f452245"),
                            CustomerName = "Fiorenze Behne",
                            OrderDate = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2023_1",
                            TotalAmount = 306.60m
                        },
                        new
                        {
                            OrderID = new Guid("4a62dddc-8fdd-4aeb-96f5-a03311348293"),
                            CustomerName = "Eugenio Fieldstone",
                            OrderDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2023_4",
                            TotalAmount = 1088.40m
                        },
                        new
                        {
                            OrderID = new Guid("7ad6b3ae-d67c-46f4-9561-f4cd129eca98"),
                            CustomerName = "Berkly Sterricks",
                            OrderDate = new DateTime(2023, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2023_5",
                            TotalAmount = 637.70m
                        },
                        new
                        {
                            OrderID = new Guid("1be791b6-7578-4d2d-92b8-b4c9d5300dc1"),
                            CustomerName = "Rosco Lowy",
                            OrderDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2022_4",
                            TotalAmount = 40.80m
                        },
                        new
                        {
                            OrderID = new Guid("91f3d4de-2ae6-45ec-8f46-1966407403bd"),
                            CustomerName = "Lek Whellans",
                            OrderDate = new DateTime(2022, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2022_2",
                            TotalAmount = 1197m
                        },
                        new
                        {
                            OrderID = new Guid("a16409c9-d498-4469-b8f5-5b7348fb7034"),
                            CustomerName = "Quentin Spiaggia",
                            OrderDate = new DateTime(2023, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2023_3",
                            TotalAmount = 94.50m
                        },
                        new
                        {
                            OrderID = new Guid("f8a55368-f4f4-4ce8-a26e-4139fa9fa6bb"),
                            CustomerName = "Lynea Middas",
                            OrderDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "Order_2023_2",
                            TotalAmount = 1812m
                        });
                });

            modelBuilder.Entity("Orders.WebAPI.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            OrderItemID = new Guid("73fe9e15-2238-4689-8c43-11353a045ab7"),
                            OrderID = new Guid("538b01e3-4803-4e4a-9f3c-8ffdfa6092ab"),
                            ProductName = "Muffin Mix - Carrot",
                            Quantity = 7m,
                            TotalPrice = 14m,
                            UnitPrice = 2m
                        },
                        new
                        {
                            OrderItemID = new Guid("86d99f15-4445-495d-9064-f4422caf8f7e"),
                            OrderID = new Guid("e6f372d0-a5f5-42b0-b3a8-71726f489f51"),
                            ProductName = "Myers Planters Punch",
                            Quantity = 2m,
                            TotalPrice = 300m,
                            UnitPrice = 150m
                        },
                        new
                        {
                            OrderItemID = new Guid("10fcaeeb-9d0b-4078-be2e-224f08b1a62e"),
                            OrderID = new Guid("e6f372d0-a5f5-42b0-b3a8-71726f489f51"),
                            ProductName = "Syrup - Kahlua Chocolate",
                            Quantity = 9m,
                            TotalPrice = 90m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            OrderItemID = new Guid("80352826-a906-4ed7-b131-2a078cb102e6"),
                            OrderID = new Guid("c5cebf9d-8ca1-4f41-b85d-b2120f452245"),
                            ProductName = "Pork - Ham Hocks - Smoked",
                            Quantity = 8m,
                            TotalPrice = 281.60m,
                            UnitPrice = 35.20m
                        },
                        new
                        {
                            OrderItemID = new Guid("7dfa2b06-62ae-4859-9b31-8bd328cc631f"),
                            OrderID = new Guid("c5cebf9d-8ca1-4f41-b85d-b2120f452245"),
                            ProductName = "Water - Spring 1.5lit",
                            Quantity = 10m,
                            TotalPrice = 25m,
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            OrderItemID = new Guid("1de377e6-aced-4991-9ca5-3159a50089a5"),
                            OrderID = new Guid("4a62dddc-8fdd-4aeb-96f5-a03311348293"),
                            ProductName = "Pepper - Cayenne",
                            Quantity = 7m,
                            TotalPrice = 62.30m,
                            UnitPrice = 8.90m
                        },
                        new
                        {
                            OrderItemID = new Guid("f7f7814a-99bf-4ec8-a773-0115654bc2f4"),
                            OrderID = new Guid("4a62dddc-8fdd-4aeb-96f5-a03311348293"),
                            ProductName = "Tart Shells - Barquettes, Savory",
                            Quantity = 4m,
                            TotalPrice = 678m,
                            UnitPrice = 169.50m
                        },
                        new
                        {
                            OrderItemID = new Guid("88a37dbf-4c80-4aa2-aaa7-805ee8efd8e1"),
                            OrderID = new Guid("4a62dddc-8fdd-4aeb-96f5-a03311348293"),
                            ProductName = "Salmon - Atlantic, Fresh, Whole",
                            Quantity = 1m,
                            TotalPrice = 175m,
                            UnitPrice = 175m
                        },
                        new
                        {
                            OrderItemID = new Guid("b9bc4cde-9793-4ccd-b305-832cde69e720"),
                            OrderID = new Guid("4a62dddc-8fdd-4aeb-96f5-a03311348293"),
                            ProductName = "Snapple - Mango Maddness",
                            Quantity = 3m,
                            TotalPrice = 173.10m,
                            UnitPrice = 57.70m
                        },
                        new
                        {
                            OrderItemID = new Guid("53f45ce3-08e5-4b30-bbf6-0ed736bcee80"),
                            OrderID = new Guid("7ad6b3ae-d67c-46f4-9561-f4cd129eca98"),
                            ProductName = "Blackberries",
                            Quantity = 3m,
                            TotalPrice = 80.70m,
                            UnitPrice = 26.90m
                        },
                        new
                        {
                            OrderItemID = new Guid("ceccc0f2-bbbc-47e0-ab96-17985290786d"),
                            OrderID = new Guid("7ad6b3ae-d67c-46f4-9561-f4cd129eca98"),
                            ProductName = "Truffle Cups - Red",
                            Quantity = 8m,
                            TotalPrice = 289.60m,
                            UnitPrice = 36.20m
                        },
                        new
                        {
                            OrderItemID = new Guid("98ec3b95-7c84-4cc6-ac48-41c3ec15edba"),
                            OrderID = new Guid("7ad6b3ae-d67c-46f4-9561-f4cd129eca98"),
                            ProductName = "Potatoes - Idaho 80 Count",
                            Quantity = 18m,
                            TotalPrice = 138.60m,
                            UnitPrice = 7.70m
                        },
                        new
                        {
                            OrderItemID = new Guid("f31e87ab-aae4-40f0-8737-b0ed00d305f4"),
                            OrderID = new Guid("7ad6b3ae-d67c-46f4-9561-f4cd129eca98"),
                            ProductName = "Cheese - Cream Cheese",
                            Quantity = 4m,
                            TotalPrice = 51.60m,
                            UnitPrice = 12.90m
                        },
                        new
                        {
                            OrderItemID = new Guid("b8392c5d-65a4-4e9a-b74a-c202b996b19b"),
                            OrderID = new Guid("7ad6b3ae-d67c-46f4-9561-f4cd129eca98"),
                            ProductName = "Cheese - Havarti, Roasted Garlic",
                            Quantity = 2m,
                            TotalPrice = 77.20m,
                            UnitPrice = 38.60m
                        },
                        new
                        {
                            OrderItemID = new Guid("b6e117b2-da67-4e58-8cb3-6346b728823b"),
                            OrderID = new Guid("1be791b6-7578-4d2d-92b8-b4c9d5300dc1"),
                            ProductName = "Sprite - 355 Ml",
                            Quantity = 24m,
                            TotalPrice = 40.80m,
                            UnitPrice = 1.70m
                        },
                        new
                        {
                            OrderItemID = new Guid("67e8f4f0-f086-43b5-9d62-15e67a04292f"),
                            OrderID = new Guid("91f3d4de-2ae6-45ec-8f46-1966407403bd"),
                            ProductName = "Veal - Inside",
                            Quantity = 9m,
                            TotalPrice = 585m,
                            UnitPrice = 65m
                        },
                        new
                        {
                            OrderItemID = new Guid("12da5931-6b2d-40f5-8eb0-c6b568c07a7b"),
                            OrderID = new Guid("91f3d4de-2ae6-45ec-8f46-1966407403bd"),
                            ProductName = "Beef - Ground Lean Fresh",
                            Quantity = 4m,
                            TotalPrice = 292m,
                            UnitPrice = 73m
                        },
                        new
                        {
                            OrderItemID = new Guid("58925077-d01c-4aaf-a4f8-bd574ab5f25e"),
                            OrderID = new Guid("91f3d4de-2ae6-45ec-8f46-1966407403bd"),
                            ProductName = "Beef Striploin Aaa",
                            Quantity = 4m,
                            TotalPrice = 320m,
                            UnitPrice = 80m
                        },
                        new
                        {
                            OrderItemID = new Guid("5170af9a-9eb9-4a11-99ce-0d346dc1fdef"),
                            OrderID = new Guid("a16409c9-d498-4469-b8f5-5b7348fb7034"),
                            ProductName = "Gelatine Leaves - Envelopes",
                            Quantity = 7m,
                            TotalPrice = 94.50m,
                            UnitPrice = 13.50m
                        },
                        new
                        {
                            OrderItemID = new Guid("96f4866a-25c1-4a17-bbcb-96823976d1d3"),
                            OrderID = new Guid("f8a55368-f4f4-4ce8-a26e-4139fa9fa6bb"),
                            ProductName = "Rabbit - Frozen",
                            Quantity = 2m,
                            TotalPrice = 74m,
                            UnitPrice = 37m
                        },
                        new
                        {
                            OrderItemID = new Guid("2aec3fc0-7ba2-4fb7-ad4c-609445e06eb1"),
                            OrderID = new Guid("f8a55368-f4f4-4ce8-a26e-4139fa9fa6bb"),
                            ProductName = "Puree - Raspberry",
                            Quantity = 4m,
                            TotalPrice = 348m,
                            UnitPrice = 87m
                        },
                        new
                        {
                            OrderItemID = new Guid("2c809175-0472-4559-8e94-7b78bd4de652"),
                            OrderID = new Guid("f8a55368-f4f4-4ce8-a26e-4139fa9fa6bb"),
                            ProductName = "Wine - Masi Valpolocell",
                            Quantity = 5m,
                            TotalPrice = 1390m,
                            UnitPrice = 278m
                        });
                });

            modelBuilder.Entity("Orders.WebAPI.Entities.OrderItem", b =>
                {
                    b.HasOne("Orders.WebAPI.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Orders.WebAPI.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
